# Generated by Django 4.2.6 on 2023-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_table_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_table',
            name='my_file',
            field=models.FileField(blank=True, upload_to='my_file'),
        ),
        migrations.AlterField(
            model_name='resume_table',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='my_profile'),
        ),
    ]
