# Generated by Django 4.2.6 on 2023-10-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_table_my_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_table',
            name='my_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='resume_table',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='resume_table',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
