# Generated by Django 4.2.6 on 2023-11-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_table_my_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume_table',
            name='job_city',
        ),
        migrations.AddField(
            model_name='resume_table',
            name='job_city',
            field=models.ManyToManyField(to='resume.city'),
        ),
    ]
