# Generated by Django 4.2.6 on 2023-11-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_city_remove_resume_table_job_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_table',
            name='job_city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='resume_table',
            name='job_city',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
